Repository caioRafael/potipoints, pull requests merged in 2023-02, with the labels that each got.

#33 #32 fix: bug do f5
  src/components/MainCard/index.tsx
  src/components/RightClickMenu/index.tsx
  src/context/AuthContext.tsx
  src/hooks/useAdmin.ts
  src/service/admin/kickUser.ts
  yarn.lock
Labels: bug

#39 Feat/scoring system
  src/Pages/Room/components/CardContent/index.tsx
  src/Pages/Room/components/ContentRoom/index.tsx
  src/Pages/Room/components/HeaderContent/index.tsx
  src/Pages/Room/components/MainContent/index.tsx
  src/Pages/Room/index.tsx
  src/components/MainCard/index.tsx
  src/context/AuthContext.tsx
  src/enums/ScoringListEnum.ts
  src/hooks/useRoom.ts
  src/records/ScoringListRecord.ts
  src/service/votes/setScoringSystem.ts
  src/utils/decimal.ts
  src/utils/fibonacci.ts
Labels: bug, enhancement

#43 #21, #42 - Feat: Adicionando tooltip
  package-lock.json
  package.json
  src/Pages/Presentation/index.tsx
  src/Pages/Room/components/HeaderContent/index.tsx
  src/Pages/Room/components/HeaderContent/styles.ts
  src/components/Dropdown/styles.ts
  src/components/MainCard/index.tsx
  src/components/RightClickMenu/index.tsx
  src/components/RightClickMenu/styles.ts
  src/components/Tooltip/index.tsx
  src/components/TooltipHost/index.tsx
  src/components/TooltipHost/styles.ts
  src/components/index.ts
  src/hooks/useAdmin.ts
  src/hooks/useOnline.ts
  src/hooks/useRoom.ts
  src/service/admin/index.ts
  src/service/admin/makeUserAdmin.ts
  src/utils/calculateBestOccurrence.ts
Labels: enhancement, adjustment
